Try to ignore NoTestFoundException on Windows
Should fix this kind of error when no test ran:
```
Build failed because:
org.jenkinsci.plugins.xunit.service.NoTestFoundException: [CTest-Version 3.x (default)] - No test report file(s) were found with the pattern 'build/Testing/*/Test.xml' relative to 'C:\build\workspace\root-pullrequests-build' for the testing framework 'CTest-Version 3.x (default)'.
```